name: encodeai2024
channels:
  - defaults
  - conda-forge
dependencies:
  - einops=0.7.0
  - huggingface_hub
  - imageio
  - omegaconf=2.3.0
  - pillow=10.1.0
  - pip
  - pip:
    - git+https://github.com/tatsy/torchmcubes.git
    - git+https://github.com/ShieldMnt/invisible-watermark.git
  - rembg
  - transformers
  - trimesh=4.0.5
  - pytorch::pytorch
  - torchaudio
  - torchvision
  - accelerate
  - diffusers